language: node_js
node_js:
- '8'
env:
  global:
    secure: LSNBZiKKx4OCsM6odwC3E28QFvTBPwwHgug9NaWRsoYxcWD6lYPz3NyeIlCcPlA2oc4U06RZf0LBMBYFjF0TuOPaiEYlO+Qv+mff+ePCNwxeYWwWDxVxcafCiSAl+8rii+ImCmSR5JglSg7WZLtPQ5xS6KlJcEigtxs805cg3TNKO/VpJXp74b1LmPIpviqRWsN6r+mFykypKwiGGwdWj5kvsbczSB1Qc9hEiOpIiq3X8mgsmDWirObOZkwQ/Drhv2u4kG1C+BtCTedAC2m/nmULFI3+4+wLMZqjpWvf8B6QzZD2QOw2y3n/vwF715FuGPltapB5BPtHGwIs+kZh5zFCjr7M3V2C7Lc9zMwk08EqUFvw1a6yzBvP1RqInaHgMB6PX+w+1jLd9A1+c5jwlJt/+ZlR5iRN9C14DPeLQErIbloY0GRkbUqsHIVn340107h+GboyWiOJsy6rZZ8IjinySlYeh7MbzURkohfosfjxIhE7aH++tthVEydZjrOIIv7dOed/VXoUBPQno1g4ietO+FImMYbnupO0lsC0cRXKSlyBYb845x9SUhMJ/7OHhzbKzpZdhjBlN2m1B808VVjLBq1vLpAenBRgMP8EghbyEPkWnS7371JiFQwLYUzm9JIGNrG6rLqQF13ivceUKmv6nHcqUJMEBI9nmKxXzQE=
branches:
  only:
  - develop
  - master
cache:
  yarn: true
  directories:
  - backend
install: ci/install.sh
script: ci/script.sh
deploy:
  provider: script
  script: ci/deploy.sh
  skip_cleanup: true
  on:
    branch: master
addons:
  browserstack:
    force_local: true
    only: localhost,8080,0
    username:
      secure: KHwk9h8D0kGbOzF2G/sArtjZQxfb/OUEN9zO7dUm5SRSX4Z3hAwixlTJx3u5i8qUdwLsGYxFEvGqJ8/nBMPUYfyZSHEYx8freUPOG+o+blsqj5ZIcHPjzxymKTAMtSg5fpaLbYvbFyfbUsQMRjWuRf91ef/h5g4yGA4PCEhUWjVe4f7cx8YquuPSfJx/pGnCihFvD/yQL6SmF7ixg6/vmv621OOyL/PNTTTsmCj563Xkt+KQgg6ZaufU1ZG9wWCjDauy6fWeCteIfx2a0ZpD8oHsxTVSGekjl1KUfTuR506G/uUPl2FbV1t7/oM9cq+A+VQCFJl5fjO6wnnXF2wBTPeFukgSoJII5LdlfRcu3DDPHLlu9AgnyXPdyVC+k3M9BRp4yHR/bPgab1SjmjLLaAkuImRcOj2cs+9dPB5v/lBNkuSk/q10Jycl3s5tutG9tV+qzL1SodrWGzmRdhIZtMHpN6eJlu4cO8MWB/28gsQnzAhVDktJXX4e241kqRGfXN7xDBu2VFFr9fkdgEN/rYQV1AqGkzB3A7iaVaNWLhDhGTmLGdVn37sI8fHkpzckaH3F4roYNWkn+4/LIfd4lReBtfXVitW4+/s+4lzTLA+1OfyXp/3ZKiRWMDPQrVPpiSf/5wxf6c3jkgri6lylbXXNDnN9dbkiGtXvzBOY7eE=
    access_key:
      secure: HimMH7D80hl+yMYuLZH3RUp1/rdB9pkTifQ8cMTIx2jruFUJNg+QKuqL6icMzZsYKizTI0u6ygp7L6pHSzqd5efL9KDuV/d3kCJNydmuAigVlogrsQN4XrSrZIhPtmMsE9EUt+qjja8cc1fdv4vE2/rOiHiBQy0NoCTT6Yey3HItmzNE6OJb0DwA7A43tm3HuG4VBxFC4wajatRtf7UbWG//Dqm9KHXHEvJlfbtQfTQfnUmNJovztd9uzdsfDRw54uWIAUIxnR5L1P+vT4ynp9t7vOPPl1MvZDyNN3wol+V2o4rLuypaKB8dTd/KM8kBcLKrSoT03YXDiB+BKRXWK1t3WQxqjrrjXnsFTfC9U4Yo3913oI8l3ntUh+E+I46hUFOp7DbR2OCFWYodqQz0UM+kDAheeAiuxMJn5TH+uGR9RJqXENTZGfyrq+Zng2TBwCaTJwz1BGgmZdhsle0/Lq2BSCgDIP12Eh16AtKkMw9JFNgU9adL0RFXBdzpnXo0k+AA1fXrLntMDfKNfcAOzmVolWTy1tn0lMij6OcPt1rXzWaKAdypF5TwRMa1dA9bxBS4lvXWsLrVQIEmCe+hasezziREg6ut2+joui3QUR4jis39WwMo/c569oZrdy7RQ23K4AFmXeleSXESh5XfWpA/ppYWFn2uf30bTOOLLMk=
